UPDATE FN71896.BRANCHES SET ADDRESS = 'Sofia, Vitosha district' WHERE BRANCH_ID = 1;
UPDATE FN71896.BRANCHES SET ADDRESS = 'Sofia, Lozenets district' WHERE BRANCH_ID = 2;
UPDATE FN71896.BRANCHES SET ADDRESS = 'VARNA' WHERE BRANCH_ID = 22;
UPDATE FN71896.BRANCHES SET ADDRESS = 'BURGAS' WHERE BRANCH_ID = 23;
UPDATE FN71896.BRANCHES SET ADDRESS = 'VIDIN, BUL. BULGARIA' WHERE BRANCH_ID = 41;