UPDATE FN71896.EMPLOYEES SET EMPLOYEE_NAME = 'Jivka', POSITION = 'Receptionist', SALARY = 1300, BRANCH_ID = 1 WHERE EMPLOYEE_ID = 1;
UPDATE FN71896.EMPLOYEES SET EMPLOYEE_NAME = 'Manol', POSITION = 'Vet Doctor', SALARY = 3000, BRANCH_ID = 2 WHERE EMPLOYEE_ID = 2;
UPDATE FN71896.EMPLOYEES SET EMPLOYEE_NAME = 'VANYO', POSITION = 'VET_OPERATION_DOCTOR', SALARY = 2500, BRANCH_ID = 22 WHERE EMPLOYEE_ID = 3;
UPDATE FN71896.EMPLOYEES SET EMPLOYEE_NAME = 'DANYO', POSITION = 'VET_BIRTH_DOCTOR', SALARY = 2500, BRANCH_ID = 22 WHERE EMPLOYEE_ID = 4;