UPDATE FN71896.PETS SET PET_NAME = 'Mason', PET_TYPE = 'Dog', PET_BREED = 'Husky', PET_SEX = 'M', PET_AGE = 3, PET_OWNER = 1 WHERE PET_ID = 1;
UPDATE FN71896.PETS SET PET_NAME = 'Puffy', PET_TYPE = 'Cat', PET_BREED = 'Persian', PET_SEX = 'F', PET_AGE = 3, PET_OWNER = 2 WHERE PET_ID = 2;
UPDATE FN71896.PETS SET PET_NAME = 'PEPI', PET_TYPE = 'COW', PET_BREED = 'HOME_COW', PET_SEX = 'F', PET_AGE = 3, PET_OWNER = 21 WHERE PET_ID = 23;
UPDATE FN71896.PETS SET PET_NAME = 'MUCI', PET_TYPE = 'MONKEY', PET_BREED = 'WILD', PET_SEX = 'F', PET_AGE = 3, PET_OWNER = 21 WHERE PET_ID = 26;
UPDATE FN71896.PETS SET PET_NAME = 'POLI', PET_TYPE = 'DOG', PET_BREED = 'HOME_BREED', PET_SEX = 'F', PET_AGE = 3, PET_OWNER = 22 WHERE PET_ID = 27;
UPDATE FN71896.PETS SET PET_NAME = 'PAPI', PET_TYPE = 'DOG', PET_BREED = 'HOME_BREED', PET_SEX = 'F', PET_AGE = 3, PET_OWNER = 22 WHERE PET_ID = 28;