UPDATE FN71896.V_EMPLOYEE_BRANCH SET EMPLOYEE_ID = 1, EMPLOYEE_NAME = 'Jivka', ADDRESS = 'Sofia, Vitosha district';
UPDATE FN71896.V_EMPLOYEE_BRANCH SET EMPLOYEE_ID = 2, EMPLOYEE_NAME = 'Manol', ADDRESS = 'Sofia, Lozenets district';
UPDATE FN71896.V_EMPLOYEE_BRANCH SET EMPLOYEE_ID = 3, EMPLOYEE_NAME = 'VANYO', ADDRESS = 'VARNA';
UPDATE FN71896.V_EMPLOYEE_BRANCH SET EMPLOYEE_ID = 4, EMPLOYEE_NAME = 'DANYO', ADDRESS = 'VARNA';